"""Genera la guia imprimible vigente de montaje y pruebas de PROJECT DOMUS."""
from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output" / "pdf" / "DOMUS_Ronda_B01-B05_sin_compras.pdf"
OUT.parent.mkdir(parents=True, exist_ok=True)

NAVY = colors.HexColor("#11263D"); BLUE = colors.HexColor("#117C8A")
GREEN = colors.HexColor("#DDF4E5"); AMBER = colors.HexColor("#FFF0C7")
RED = colors.HexColor("#FFE0DB"); PALE = colors.HexColor("#EAF4F6")
styles = getSampleStyleSheet()
title = ParagraphStyle("title", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=24, leading=28, textColor=NAVY, alignment=TA_CENTER)
h1 = ParagraphStyle("h1", parent=styles["Heading1"], fontSize=16, leading=19, textColor=NAVY, spaceAfter=7)
h2 = ParagraphStyle("h2", parent=styles["Heading2"], fontSize=11, leading=14, textColor=BLUE, spaceBefore=4, spaceAfter=4)
body = ParagraphStyle("body", parent=styles["BodyText"], fontSize=8.4, leading=11, textColor=colors.HexColor("#243443"), spaceAfter=5)
small = ParagraphStyle("small", parent=body, fontSize=7.2, leading=9)
mono = ParagraphStyle("mono", parent=body, fontName="Courier", fontSize=7.1, leading=9, backColor=colors.HexColor("#F1F5F7"), borderPadding=6)

def p(text, style=body): return Paragraph(text, style)
def table(rows, widths=None, header=True, fs=7.2):
    t = Table([[p(str(c), small) for c in row] for row in rows], colWidths=widths, repeatRows=1 if header else 0, hAlign="LEFT")
    cmds = [("VALIGN",(0,0),(-1,-1),"TOP"),("GRID",(0,0),(-1,-1),0.45,colors.HexColor("#A9BBC5")),("LEFTPADDING",(0,0),(-1,-1),4),("RIGHTPADDING",(0,0),(-1,-1),4),("TOPPADDING",(0,0),(-1,-1),3),("BOTTOMPADDING",(0,0),(-1,-1),3)]
    if header: cmds += [("BACKGROUND",(0,0),(-1,0),NAVY),("TEXTCOLOR",(0,0),(-1,0),colors.white)]
    for i in range(1 if header else 0, len(rows)):
        if i % 2 == 0: cmds.append(("BACKGROUND",(0,i),(-1,i),colors.HexColor("#F4F8FA")))
    t.setStyle(TableStyle(cmds)); return t

def box(text, color):
    t=Table([[p(text, body)]], colWidths=[176*mm]); t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),color),("BOX",(0,0),(-1,-1),0.7,NAVY),("LEFTPADDING",(0,0),(-1,-1),7),("RIGHTPADDING",(0,0),(-1,-1),7),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6)])); return t

def page_num(canvas, doc):
    canvas.saveState(); canvas.setFont("Helvetica",7); canvas.setFillColor(colors.grey)
    canvas.drawString(18*mm, 10*mm, "PROJECT DOMUS | Guia vigente 2026-09-10")
    canvas.drawRightString(198*mm, 10*mm, f"Pagina {doc.page}"); canvas.restoreState()

S=[]
S += [Spacer(1,18*mm), p("PROJECT DOMUS", title), p("GUIA COMPLETA DE MONTAJE Y PRUEBAS", ParagraphStyle("sub", parent=title, fontSize=13, leading=17, textColor=BLUE)), Spacer(1,8*mm), box("Version vigente: inventario confirmado y fotografiado. No presupone TA6586 ni piezas del kit SunFounder que no hayan sido identificadas fisicamente.", GREEN), Spacer(1,5*mm), p("Objetivo", h1), p("Montar ahora sensores, LCD I2C, control IR, botones, LED y buzzer; probar por separado las piezas dudosas; y dejar documentado el salto al sistema final con DRV8833, fuente 5 V/5 A y audio MAX98357A."), box("REGLA DE ORO: ningun motor se alimenta desde un GPIO, 3V3 o 5V del ESP32. Durante el banco actual bomba y ventilador quedan fuera del montaje simultaneo hasta tener un controlador y una fuente adecuados.", RED), p("Estados usados",h2), table([["Estado","Significado"],["YA CONECTAR","Parte identificada y de bajo riesgo"],["PROBAR APARTE","No integrar hasta identificar pinout/comportamiento"],["COMPRA PENDIENTE","Solo aparece en el plano final"],["NO USAR","Ruta descartada o insegura"]],[38*mm,138*mm])]
S += [PageBreak(), p("1. Mapa casi terminado con lo que ya tienes",h1), p("Todas las tierras del banco se unen a GND del ESP32. El ESP32 se alimenta por USB. No conectar otra fuente positiva al mismo tiempo."), p("ESP32-S3 N16R8 (USB)<br/>|-- 3V3: LCD VCC, DHT11, suelo, nivel, LDR, PIR, HX1838<br/>|-- GND: retorno comun de todos los anteriores y controles<br/>|-- GPIO21 SDA + GPIO13 SCL: LCD I2C, solo cuatro cables<br/>|-- GPIO1 suelo AO | GPIO2 nivel S | GPIO3 divisor LDR<br/>|-- GPIO9 PIR OUT | GPIO14 DHT DATA | GPIO12 HX1838 OUT<br/>|-- GPIO10 STOP->GND | GPIO11 MUTE->GND<br/>|-- GPIO5 LED sala | GPIO6 LED dormitorio<br/>|-- GPIO8 -> S8050 -> tres LED cultivo<br/>`-- GPIO15 -> segundo S8050 -> buzzer activo 5 V (o buzzer pasivo solo como alternativa)",mono), box("Bomba, ventilador, rele desnudo y transistor sin marca se prueban por separado. No forman parte de este bus simultaneo.",AMBER), p("Mapa final despues de comprar",h2), p("Fuente cerrada 5 V/5 A -> fusible lento 4 A -> switch maestro -> bus 5 V. Del bus salen ramales al ESP32, DRV8833, MAX98357A y cargas. GND comun. El DRV8833 maneja bomba y ventilador; no se compran reles." )]
S += [PageBreak(), p("2. Tabla maestra de pines",h1), table([["GPIO","Conexion exacta","Modo"],["1","AO sensor de suelo","ADC"],["2","S sensor de nivel","ADC"],["3","Nodo LDR + resistor 10 k a GND","ADC"],["4","DRV AIN1 (solo final)","Salida"],["5","LED sala: GPIO-resistor 330-anodo; catodo-GND","Salida"],["6","LED dormitorio: igual","Salida"],["7","DRV BIN1 (solo final)","Salida"],["8","Resistor 1 k a base S8050 cultivo","Salida"],["9","OUT PIR","Entrada"],["10","Boton STOP normalmente abierto a GND","INPUT_PULLUP"],["11","Boton MUTE normalmente abierto a GND","INPUT_PULLUP"],["12","OUT receptor IR HX1838","Entrada"],["13","SCL LCD I2C","I2C"],["14","DATA DHT11","Digital"],["15","1 k a base S8050 de buzzer","Salida"],["16","BCLK MAX98357A (final)","I2S"],["17","LRC MAX98357A (final)","I2S"],["18","DIN MAX98357A (final)","I2S"],["21","SDA LCD I2C","I2C"]],[20*mm,118*mm,35*mm]), p("Pines reservados 4, 7, 16, 17 y 18 se mantienen sin carga en el esqueleto actual. Confirmar siempre la serigrafia de la placa real.",small)]
S += [PageBreak(), p("3. Sensores y LCD: conexion exacta",h1), table([["Pieza","VCC","GND","Senal"],["LCD1602 + backpack I2C","3V3","GND","SDA->21, SCL->13"],["DHT11 modulo","3V3","GND","DATA/S->14"],["Suelo resistivo","3V3","GND","AO->1; DO libre"],["Nivel de agua","3V3","GND","S/AO->2"],["PIR","3V3","GND","OUT->9"],["HX1838","3V3","GND","OUT/S->12"]],[47*mm,28*mm,28*mm,73*mm]), p("LDR en divisor",h2), p("3V3 -> LDR -> NODO -> resistor 10 kOhm -> GND. NODO -> GPIO3. Si el valor cambia al reves de lo esperado, se corrige la comparacion del firmware; no se sube el ADC a 5 V."), box("El LCD observado funciona a 3.3 V: usar solamente GND, VCC, SDA y SCL. No conectar ademas los 16 pines paralelos. Ajustar el potenciometro del backpack si hay luz pero no caracteres.",GREEN), p("DHT11 suelto",h2), p("Mirando la rejilla frontal, el orden usual es VCC, DATA, NC, GND, pero los modulos de tres pines pueden variar. Leer la serigrafia. Un sensor suelto requiere pull-up de 10 kOhm entre DATA y 3V3."), p("Sensores analogicos",h2), p("Calibrar con lecturas reales. Registrar suelo seco/humedo, nivel vacio/seguro y LDR cubierto/iluminado. Nunca aceptar 0 o 4095 fijo como lectura valida sin diagnostico." )]
S += [PageBreak(), p("4. Luces, transistores, diodos y buzzer",h1), p("LED directos de sala/dormitorio",h2), p("GPIO5 o GPIO6 -> resistor 330 Ohm -> anodo (pata larga). Catodo (pata corta y lado plano) -> GND. Un resistor por LED."), p("Tres LED de cultivo con S8050",h2), p("+5 V -> un resistor 330 Ohm por LED -> anodo de cada LED. Los tres catodos -> colector C del S8050. Emisor E -> GND. GPIO8 -> resistor 1 kOhm -> base B. Base -> resistor 10 kOhm -> GND. Antes de soldar, identificar E/B/C del ejemplar real; el encapsulado no garantiza el orden."), p("Buzzer activo TMB12A05",h2), p("+5 V -> positivo del buzzer. Negativo -> colector del segundo S8050. Emisor -> GND. GPIO15 -> 1 kOhm -> base; base -> 10 kOhm -> GND. El buzzer pasivo se prueba como alternativa y no se conecta simultaneamente."), p("Diodos",h2), table([["Uso","Orientacion"],["Motor DC o bomba","En paralelo con motor: catodo/raya al lado positivo, anodo al negativo"],["Bobina de rele suelta (solo prueba)","En paralelo con bobina: catodo/raya a positivo"],["LED","Anodo largo hacia positivo; catodo corto/lado plano hacia GND"]],[52*mm,124*mm]), box("Un diodo instalado al reves sobre la alimentacion produce un corto. Desconectar de inmediato si se calienta.",RED)]
S += [PageBreak(), p("5. Jarvis confiable: control CAR MP3",h1), p("El receptor HX1838 convierte cada tecla en una orden. No hay wake word, microfono ni entrenamiento de IA. El firmware reproduce una frase espanola fija cuando el MAX98357A este disponible."), table([["Tecla","Accion propuesta"],["CH- / CH / CH+","Manual / pagina LCD / automatico"],["Anterior / Siguiente","Luz sala / luz dormitorio"],["Play-Pause","Repetir o pausar audio"],["VOL- / VOL+","Bajar / subir volumen"],["EQ","Diagnostico"],["0 / 100+ / 200+","Todo OFF / silencio / rearme"],["1 / 2 / 3","Sala / dormitorio / cultivo"],["4 / 5","Ventilador / solicitud de riego"],["6 / 7 / 8 / 9","Temperatura / humedad / suelo-nivel / estado"]],[52*mm,124*mm]), p("Primero cargar domus_ir_learn, pulsar cada tecla una vez y anotar el codigo real. No copiar HEX de internet. Ignorar tramas REPEAT para riego, rearme y cambios de modo. STOP fisico siempre tiene prioridad."), box("Frases esperadas: 'He encendido la luz de sala', 'Riego bloqueado por nivel bajo', 'Sistema en modo automatico'. La accion funciona aunque el audio este silenciado.",PALE)]
S += [PageBreak(), p("6. Piezas disponibles que se prueban aparte",h1), table([["Pieza","Como probar","Decision"],["Bomba 3-6 V","Sumergida, pulso breve con fuente adecuada; nunca en seco","Guardar para DRV8833"],["Ventilador/motor","Fuente adecuada, observar polaridad y arranque","Guardar para DRV8833"],["Rele desnudo","Identificar bobina por resistencia; energizar solo con transistor+diodo","No integrar al proyecto"],["Transistor sin marca","Multimetro/modo diodo; no asumir BJT o MOSFET","No integrar hasta identificar"],["Buzzer pasivo","Tono PWM corto con etapa adecuada","Alternativa al activo"],["74HC595, displays, matriz, RGB, servo, joystick, RFID, MPU6050","Ejemplos independientes","Fuera del nucleo DOMUS"],["TP4056","No usar como distribuidor permanente sin bateria","Fuera de arquitectura final"]],[43*mm,89*mm,44*mm]), p("Que el kit original liste una pieza no demuestra que tu kit modificado la incluya. Cada elemento se acepta solo por foto, serigrafia legible, medicion o prueba controlada."), p("El rele no es necesario para la bomba",h2), p("El DRV8833 es mas apropiado para cargas DC pequenas: conmuta electronicamente, admite PWM y elimina el desgaste/clic del rele. El rele suelto queda como practica de identificacion, no como parte de la maqueta." )]
S += [PageBreak(), p("7. Montaje final despues de las compras",h1), p("Potencia",h2), p("Toma AC -> adaptador cerrado 5 V/5 A -> jack a tornillos -> fusible lento 4 A -> switch maestro DC -> BUS 5V. Distribuir +5 V y GND por borneras. Colocar 1000 uF cerca del DRV8833 y otro cerca del MAX98357A, respetando polaridad."), p("DRV8833",h2), p("VM->5V, GND->GND, nSLEEP->3V3. AIN1->GPIO4 y AIN2->GND; bomba entre AOUT1/AOUT2. BIN1->GPIO7 y BIN2->GND; ventilador entre BOUT1/BOUT2. Confirmar nombres del modulo exacto: algunos clones invierten el orden o exponen FAULT."), p("Audio",h2), p("MAX98357A VIN->5V, GND->GND, BCLK->GPIO16, LRC/WS->GPIO17, DIN->GPIO18. Parlante de 4 Ohm/3 W solamente entre SPK+ y SPK-; ninguno a GND."), box("Antes de unir el ESP32: fuente sola, polaridad correcta, 5 V medidos, fusible y switch probados. Alimentar el ESP32 por una sola ruta positiva. Todos los GND deben ser comunes.",RED), p("Compras pendientes",h2), p("DRV8833, fuente cerrada 5 V/5 A con adaptador, MAX98357A, parlante, baquelita, borneras, portafusible, dos fusibles lentos 4 A y cinco capacitores 1000 uF/25 V/105 C. No comprar INMP441, reles adicionales ni sensor UV." )]
S += [PageBreak(), p("8. Que firmware usar en cada etapa",h1), table([["Firmware","Hardware","Proposito"],["domus_selftest","ESP32 solo por USB","Arranque, serial, memoria y estabilidad"],["domus_esqueleto","Sensores + LCD, salidas fisicas bloqueadas","Lecturas, calibracion y fallos seguros"],["domus_ir_learn","HX1838 + control","Registrar los 21 codigos reales"],["domus_actuator_test","Fuente + DRV + una carga cada vez","Direccion, PWM, timeout y paro"],["domus_audio_test","MAX98357A + parlante","Tono y frases desde flash"],["casa_inteligente_v4","Todo aprobado","Automatizacion final + IR + audio"]],[42*mm,65*mm,69*mm]), p("El esqueleto no se convierte en final cambiando un solo false. El final debe implementar perfiles, arranque OFF, nivel minimo, timeout de bomba, rearmado manual, histéresis, horario de cultivo, watchdog y rechazo de sensores invalidos."), p("Orden de desarrollo",h2), p("1) congelar mapa GPIO; 2) calibrar entradas; 3) aprender IR; 4) probar DRV; 5) probar audio; 6) integrar control manual; 7) integrar automatico; 8) prueba de una hora; 9) congelar firmware de feria."), p("Fuente de verdad",h2), p("Consultar la nota Obsidian '44 - Arquitectura y ciclo de vida del firmware'. El HTML interactivo sirve como plano navegable; esta guia es la copia imprimible." )]
S += [PageBreak(), p("9. Secuencia de prueba y criterios PASS",h1), table([["Paso","Prueba","PASS"],["1","Inspeccion sin corriente","Sin puentes accidentales ni electroliticos invertidos"],["2","Continuidad 5V-GND","No hay corto"],["3","ESP32 solo, selftest","Sin reinicios"],["4","LCD a 3V3","0x27/0x3F y texto estable"],["5","Un sensor cada vez","Lectura cambia y desconexion no activa cargas"],["6","STOP y MUTE","LOW al pulsar; STOP domina"],["7","HX1838","21 teclas registradas sin HEX inventado"],["8","LED individuales","Polaridad/resistencia correctas"],["9","Etapas S8050","Apagadas al arranque; sin calentamiento"],["10","Fuente final sola","5 V, polaridad y fusible correctos"],["11","DRV sin y con una carga","No calienta; timeout funciona"],["12","Bomba+ventilador","Sin caida sostenida ni reset"],["13","MAX98357A","Audio claro; MUTE no bloquea accion"],["14","Sistema completo 60 min","Cero resets, humo, olor o cables calientes"]],[15*mm,80*mm,81*mm]), box("Detener inmediatamente ante humo, olor, cable o componente caliente, reinicios repetidos, agua cerca de la electronica o tension fuera de rango.",RED)]
S += [PageBreak(), p("10. Registro de feria y diagnostico",h1), table([["Dato","Resultado"],["Direccion LCD","____________________________"],["LDR claro / oscuro","____________ / ____________"],["Suelo seco / humedo","____________ / ____________"],["Nivel vacio / seguro","____________ / ____________"],["Codigos IR guardados","archivo/version: __________________"],["5 V sin carga / con motores","____________ / ____________"],["Duracion prueba completa","____________ min"],["Reinicios / fallos","____________________________"]],[70*mm,106*mm]), p("Diagnostico rapido",h2), table([["Sintoma","Revisar"],["LCD sin texto","3V3, GND, contraste, SDA21, SCL13, direccion"],["ADC fijo","AO/S, 3V3, GND, humedad o saturacion"],["IR no responde","orden S/VCC/GND del receptor y codigo aprendido"],["LED no enciende","anodo/catodo, resistor y E/B/C real"],["Bomba no gira","agua, VM, nSLEEP, AIN1 y corriente de arranque"],["ESP se reinicia","caida de 5 V, GND, cable fino o desacoplo"],["Audio distorsiona","parlante, ganancia, fuente y capacitor cercano"]],[56*mm,120*mm]), box("Este documento no sustituye leer la serigrafia ni medir. Si el modulo fisico no coincide con el dibujo, manda el modulo: detenerse, identificar y actualizar el plano.",AMBER)]

doc=SimpleDocTemplate(str(OUT), pagesize=letter, rightMargin=17*mm,leftMargin=17*mm,topMargin=15*mm,bottomMargin=16*mm, title="PROJECT DOMUS - Guia completa de montaje y pruebas", author="PROJECT DOMUS")
doc.build(S,onFirstPage=page_num,onLaterPages=page_num)
print(OUT)
